# Generated by Django 5.1.2 on 2024-10-31 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_self_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='self_game',
            name='зщые',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
