# Generated by Django 5.1.2 on 2024-10-31 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_self_game_зщые'),
    ]

    operations = [
        migrations.RenameField(
            model_name='self_game',
            old_name='зщые',
            new_name='post',
        ),
    ]
