# Generated by Django 5.1.2 on 2024-11-11 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_self_game_stastavka_self_game_timelimit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='self_game',
            name='description',
            field=models.TextField(default='', verbose_name='Описание спора'),
        ),
    ]
